### ISSUE TITLE
Is this still supported? 2 issues open 5 for 5 months.

### ISSUE THREAD

**Issue by cmwwebfx** [slobodan/WordPress-Theme-Customizer-Boilerplate#11]
Hi, is this boilerplate still supported? Seems there are issues not resolved for 5 months.

**Comment by slobodan** [comment]
Not actively developed at the moment, sorry

**Comment by cmwwebfx** [comment]
Then why not close this or make it private so other developers do not try use some code that is no longer supported. Alternatively update the home page to say:

## Sorry, this is no longer Supported
Please feel free to use the code or fork it to continue development.

**Comment by slobodan** [comment]
That's a good point, and I should've done that. Setting it to private for now.

Thanks.
